CREATE TABLE SEASON_PLAYERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PLAYER_ID VARCHAR(36) NOT NULL,
    SEASON_START_YEAR INT NOT NULL,
    TEAM_ID VARCHAR(300) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    CM_HEIGHT INTEGER,
    POSITION VARCHAR(32) NOT NULL,
    NATIONALITY VARCHAR(50),
    INJURY_PLAYER_TYPE_NAME VARCHAR(50),
    UNIQUE (PLAYER_ID, SEASON_START_YEAR, TEAM_ID),
    INDEX (NAME),
    INDEX (TEAM_ID)
);
-- NOTE: NO START DATE FOR PLAYER ON TEAM SO CAN'T DISTINGUISH FULL SEASON ON TEAM

CREATE TABLE TEAMS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    OFFICIAL_NAME VARCHAR(100) NOT NULL,
    LEAGUE_NAME VARCHAR(100) NOT NULL,
    UNIQUE INDEX (LEAGUE_NAME, OFFICIAL_NAME),
    INDEX (OFFICIAL_NAME)
);

CREATE TABLE MATCH_STATS (
    ID VARCHAR(36) NOT NULL,
    TEAM_ID VARCHAR(36) NOT NULL,
    SEASON_START_YEAR INT NOT NULL,
    GAME_DATE DATE NOT NULL,
    FIXTURE_NUMBER INTEGER NOT NULL,
    IS_HOME BOOLEAN NOT NULL,
    WON_POINTS INTEGER NOT NULL,
    GOALS INTEGER NOT NULL,
    ASSISTS INTEGER NOT NULL,
    YELLOW_CARDS INTEGER NOT NULL,
    RED_CARDS INTEGER NOT NULL,
    CONSTRAINT PRIMARY KEY (ID, TEAM_ID),
    UNIQUE INDEX (TEAM_ID, GAME_DATE)
);

CREATE TABLE PLAYER_GAME_STATS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    SEASON_PLAYER_ID VARCHAR(36) NOT NULL,
    MATCH_ID VARCHAR(36) NOT NULL,
    PLAYED_MINUTES INTEGER NOT NULL,
    GOALS INTEGER,
    ASSISTS INTEGER,
    YELLOW_CARDS INTEGER,
    RED_CARDS INTEGER,
    STARTED BOOLEAN NOT NULL,
    SUBBED BOOLEAN NOT NULL,
    UNIQUE KEY (SEASON_PLAYER_ID, MATCH_ID)
);

CREATE TABLE PLAYER_INJURIES (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    SEASON_PLAYER_ID VARCHAR(36) NOT NULL,
    INJURY_TYPE_NAME VARCHAR(50) NOT NULL,
    IS_MUSCULAR_INJURY BOOLEAN NOT NULL,
    INCLUSIVE_BEGIN_DATE DATE NOT NULL,
    INCLUSIVE_END_DATE DATE NOT NULL,
    UNIQUE INDEX (SEASON_PLAYER_ID, INCLUSIVE_BEGIN_DATE, INJURY_TYPE_NAME)
);
